[package]
name = "bloop"
version = "0.1.0"
authors = ["Blaine <rishi1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { path = "webview" , features = ["edge"]}
