[package]
name = "bloop"
version = "0.1.0"
authors = ["Blaine <rishi1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { git = "https://github.com/Blakeinstein/web-view/" , features = ["edge"]}
rust-embed = "5.5.1"
serde_json = "1.0.56"
serde = { version = "1.0.114", features = ["derive"] }
