[global]
custom_css = ""
width = 900
height = 400

[vars]
font = '"SF mono", "Cascadia Code", "CascadiaCode Nerd Font", "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif'
font_size = '30px'
editor_font_size = '20px'
gutter_size = '4.2rem'
gutter_color = '#161616c2'
editor_color = '#1f1f1fc2'
gutter_text_color = '#999'
editor_text_color = 'white'
seperator_width = '1.2px'
seperator_color = '#f0f0fe2'
# syntax
syntax_comment = '#888ea6'
syntax_string = '#ff4c7c'
syntax_attribute = '#4cffb2'
syntax_number = '#ffb24c'
syntax_extra = '#3586ff'
syntax_keyword = '#32ff47'